name: Maven CI

on:
  workflow_dispatch: { }
  push: { }
  pull_request: { }

# Minimum permissions required by skip-duplicate-actions
permissions:
  actions: write
  contents: read

jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'same_content_newer'
          skip_after_successful_duplicate: 'true'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  build:
    needs: pre_job
    runs-on: [ubuntu-latest]
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 22
          distribution: temurin

      - name: Build application with Maven
        shell: bash
        run: |
          ./mvnw \
            --show-version \
            --errors \
            --batch-mode \
            --no-transfer-progress \
            spotless:check \
            verify \
            -DtrimStackTrace=false

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3


